# Generated by Django 4.1.5 on 2023-01-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='New_place',
        ),
    ]
