# Generated by Django 4.1.5 on 2023-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0002_rename_place_new_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='New_place',
        ),
    ]
