# Generated by Django 4.1.5 on 2023-01-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0003_new_places_delete_new_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_places',
            new_name='tour',
        ),
    ]
