# Generated by Django 4.1.5 on 2023-01-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0004_rename_new_places_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
